create table dogs ( id serial primary key ,name varchar not null,age int not null);
insert into dogs( name, age) values ('boby', 2);
create table puppies (id serial primary key , name varchar(64) not null ,age int not null,dogs_id int references dogs(id));
insert into puppies (name, age, dogs_id) values ('qwer', 1, 1);
create table cats (id serial primary key ,name varchar(64) not null ,age int not null );
insert into cats (name, age) values ('nun', 3);
create table kitties (id serial primary key, name varchar(64) not null, age int not null, cats_id int references cats(id));
insert into kitties(name, age, cats_id) values ('qw', 1, 1);
create table cows (id serial primary key, name varchar, age int not null);
insert into cows (name, age) values ('sa', 10);
create table the_calf (id serial primary key, name varchar not null , age int not null, cows_id int references cows(id));
insert into the_calf(name, age, cows_id) values ('po', 7, 1);
create table horses (id serial primary key, name varchar(64) not null, age int not null);
insert into horses(name, age) values ('qq', 9);
create table baby_horse(id serial primary key, name varchar not null, age int not null, horses_id int references horses(id));
insert into baby_horse(name, age, horses_id) values('zz', 4, 1);
create table fox(id serial primary key, name varchar not null, age int not null);
insert into fox(name, age) values ('fox', 20);
create table wolf(id serial primary key, name varchar not null, age int not null, for_id int references fox(id));
insert into wolf(name, age, for_id) values ('ee', 13, 1);